SET DEFINE OFF

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (1.0, 1.0, 1.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (2.0, 1.0, 3.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (3.0, 2.0, 5.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (4.0, 3.0, 3.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (5.0, 1.0, 6.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (6.0, 3.0, 4.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (7.0, 5.0, 2.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (8.0, 3.0, 6.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (9.0, 5.0, 3.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (10.0, 5.0, 5.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (11.0, 3.0, 8.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (12.0, 7.0, 4.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (13.0, 4.0, 7.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (14.0, 2.0, 4.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (15.0, 7.0, 7.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (16.0, 2.0, 3.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (17.0, 7.0, 9.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (18.0, 4.0, 4.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (19.0, 7.0, 7.0);

INSERT INTO CAST (CASTID, EMPLOYEEID, MEDIAID) 
VALUES (20.0, 9.0, 3.0);

-- Import Data into table CAST from file C:\Users\t00193170\Desktop\SQL FILES FINAL\Population\CastPop.csv . Task successful and sent to worksheet.
