SET DEFINE OFF

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (1.0, 'Lion King', 1997.0, '18', 1500000.0, 'Action', 'Thriller', 'F', '', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (2.0, 'Matrix', 1993.0, 'PG', 900000.0, 'Drama', 'Action', 'F', '', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (3.0, 'ConeHeads', 1993.0, '15', 15000.0, 'Action', 'Romance', 'F', '', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (4.0, 'Den of Thieves', 2004.0, '12', 123000.0, 'Romance', 'Drama', 'G', 'PS4', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (5.0, 'Cargo', 2013.0, 'PG', 123123.0, 'Action', 'Horror', 'G', 'XBOX ONE', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (6.0, 'Gran Torino', 1982.0, 'U', 111456.0, 'Thriller', 'Kids', 'F', '', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (7.0, 'I Love You Man', 1987.0, '12', 1234567.0, 'Action', 'Kids', 'G', 'PC', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (8.0, 'VS', 2018.0, '12A', 200000.0, 'Horror', 'Music', 'F', '', 0.0);

INSERT INTO MEDIA (MEDIAID, NAME, YEARRELEASED, AGERATING, BUDGET, PRIMARYGENRE, SECONDARYGENRE, MEDIATYPE, PLATFORM, AVERAGERATING) 
VALUES (9.0, '8 Mile', 2007.0, 'PG', 12000.0, 'Action', 'Drama', 'G', 'PC', 0.0);

-- Import Data into table MEDIA from file C:\Users\t00193170\Desktop\SQL FILES FINAL\Population\MediaPop.csv . Task successful and sent to worksheet.
