SET DEFINE OFF

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (1.0, 0.0, 'SERIOUS FLICK', 'Funny', 'A', 1.0, 1.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (2.0, 0.0, 'SERIOUS FLICK', 'Good', 'A', 2.0, 1.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (3.0, 0.0, 'SERIOUS FLICK', 'Funny', 'A', 4.0, 2.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (4.0, 0.0, 'SERIOUS FLICK', 'Good', 'A', 3.0, 3.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (5.0, 0.0, 'SERIOUS FLICK', 'Bad', 'A', 6.0, 9.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (6.0, 0.0, 'SERIOUS FLICK', 'Good', 'A', 5.0, 4.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (7.0, 0.0, 'SERIOUS FLICK', 'Funny', 'A', 3.0, 8.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (8.0, 0.0, 'SERIOUS FLICK', 'Good', 'A', 6.0, 5.0);

INSERT INTO REVIEW (REVIEWID, RATING, DESCRIPTION, REVIEWTYPE, STATUS, ACCOUNTID, MEDIAID) 
VALUES (9.0, 0.0, 'SERIOUS FLICK', 'Good', 'A', 3.0, 7.0);

-- Import Data into table REVIEW from file C:\Users\t00193170\Desktop\SQL FILES FINAL\Population\ReviewPop.csv . Task successful and sent to worksheet.
